// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-debug.fsx"
#load "../Resources.fs"
      "../AssemblyInfo.fs"
      "../Common.fs"
      "../Error.fs"
      "../Expr.fs"
      "../Binding.fs"
      "../Type.fs"
      "../ExprGen.fs"
      "../BindingGen.fs"
      "../TypeGen.fs"
      "../SymbolGen.fs"
      "../CodeGen.fs"
      "../PrettyPrint.fs"
      "../FSCompiler.fs"
      "../CoreLib.FSharp.fs"
      "../CoreLib.fs"
      "../Transformation.fs"
      "../Validation.fs"
      "../Optimization.fs"
      "../Integration.fs"
